server:
  port: 8888
spring:
  application:
    name: GATEWAY
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8761"
              - "http://localhost:8887"
            allowedHeaders:
              - Content-Type
              - Authorization
            exposedHeaders:
              - Content-Type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"